refactor(tabset and tooltip): convert dev docs from less to scss
HelixDesignSystem/helix-ui pull request #778
Opened 2020-10-23 12:04 UTC by BY00565233

## Description

Refactor Tabset and Tooltip Dev Docs from LESS to SCSS

### What are the relevant story cards/tickets? Any additional PRs or other references?

Jira: SURF-2084

## Before you request a review for this PR:

- [ ] For UI changes, did you manually test in recent versions of modern browsers (Chrome, Firefox, and Safari)?
- [ ] For UI changes, did you manually test in IE11 and legacy Edge?
- [ ] Did you add component tests for any new code?
- [ ] Did you run the component unit tests via `yarn test` to ensure all tests passed?
- [ ] Did you include a screenshot of the component tests?
- [ ] If you changed/added functionality, did you update the demo page and documentation?
- [ ] If needed, did you add or modify the demo test page to test the changed/added functionality?
- [ ] Did you assign reviewers?
- [ ] In Jira, have you linked to this PR on the ticket(s)?

2020-10-26 05:39 UTC, 100stacks requested changes

2020-10-26 05:39 UTC, 100stacks commented on docs/components/tabset/_demo.scss
> +.docs-tabset {
Please use `git mv`.

2020-10-26 05:39 UTC, 100stacks commented on docs/components/tooltip/_demo.scss
> +.tooltip-appearance {
Please use `git mv`.

2020-10-26 05:39 UTC, 100stacks commented on docs/styles/demo/tabset-docs.less
> +// .docs-tabset {
Please use `git mv`.

2020-10-26 05:39 UTC, 100stacks commented on docs/styles/demo/tooltip-docs.less
> +// .tooltip-appearance {
Please use `git mv`.

2020-10-28 10:13 UTC, BY00565233 commented on docs/components/_index.scss
> +@import "tooltip/demo";
Changes have been done, Please review

2020-10-28 10:13 UTC, BY00565233 commented on docs/components/tabset/_demo.scss
> +.docs-tabset {
Changes have been done, Please review

2020-10-28 10:13 UTC, BY00565233 commented on docs/components/tooltip/_demo.scss
> +.tooltip-appearance {
Changes have been done, Please review

2020-10-28 10:13 UTC, BY00565233 commented on docs/components/tabset/_demo.scss
> +.docs-tabset {
Changes have been done, Please review

2020-10-28 10:14 UTC, BY00565233 commented on docs/components/tooltip/_demo.scss
> +.tooltip-appearance {
Changes have been done, Please review

2020-10-28 10:14 UTC, BY00565233 commented on docs/styles/demo/tabset-docs.less
> +// .docs-tabset {
Changes have been done, Please review

2020-10-28 10:14 UTC, BY00565233 commented on docs/styles/demo/tooltip-docs.less
> +// .tooltip-appearance {
Changes have been done, Please review

2020-10-28 16:39 UTC, 100stacks approved these changes
Dev LGTM

2020-10-29 12:25 UTC, lalithkarikelli approved these changes
DEV LGTM

2020-11-17 19:15 UTC, merged