docs(hx-drawer): implement and document attributes and variables
HelixDesignSystem/helix-ui pull request #794
Opened 2020-12-07 14:48 UTC by lalithkarikelli

## Description

`hx-drawer` : Implement and document attributes and variables

### What are the relevant story cards/tickets? Any additional PRs or other references?

Jira: SURF 2104

## Before you request a review for this PR:

- [ ] For UI changes, did you manually test in recent versions of modern browsers (Chrome, Firefox, and Safari)?
- [ ] For UI changes, did you manually test in IE11 and legacy Edge?
- [ ] Did you add component tests for any new code?
- [ ] Did you run the component unit tests via `yarn test` to ensure all tests passed?
- [ ] Did you include a screenshot of the component tests?
- [ ] If you changed/added functionality, did you update the demo page and documentation?
- [ ] If needed, did you add or modify the demo test page to test the changed/added functionality?
- [ ] Did you assign reviewers?
- [ ] In Jira, have you linked to this PR on the ticket(s)?

2020-12-09 09:33 UTC, BY00565233 approved these changes
DEV LGTM

2020-12-15 23:41 UTC, 100stacks requested changes

2020-12-15 23:41 UTC, 100stacks commented on src/scss/components/drawer/_index.scss
>      border-top: 1px solid $gray-400;
Please change to:

```css
border-top: 1px solid var(--hxDrawer-hxdiv-border-top, $gray-400);
```

2020-12-15 23:41 UTC, 100stacks commented on src/scss/components/drawer/_index.scss
>      border-top: 1px solid $gray-400;
Please change to:

```css
border-top: 1px solid var(--hxDrawer-footer-border-top, $gray-400);
```

2020-12-15 23:41 UTC, 100stacks commented on src/scss/components/drawer/_index.scss
> +    background-color: var(--hxDrawer-hxDiv-bgcolor, $gray-0);
Please change to:

```css
background-color: var(--hxDrawer-hxdiv-bgcolor, $gray-0);
```

2020-12-16 09:02 UTC, lalithkarikelli commented on src/scss/components/drawer/_index.scss
>      border-top: 1px solid $gray-400;
Changes have been done, please review.

2020-12-16 09:02 UTC, lalithkarikelli commented on src/scss/components/drawer/_index.scss
>      border-top: 1px solid $gray-400;
Changes have been done, please review.

2020-12-16 09:02 UTC, lalithkarikelli commented on src/scss/components/drawer/_index.scss
> +    background-color: var(--hxDrawer-hxDiv-bgcolor, $gray-0);
Changes have been done, please review.

2020-12-16 22:19 UTC, 100stacks approved these changes
Dev LGTM

2020-12-16 22:30 UTC, merged