docs(hx-choicetile): implement and document variables and attributes
HelixDesignSystem/helix-ui pull request #795
Opened 2020-12-08 13:56 UTC by lalithkarikelli

## Description

`hx-choicetile` :  implement and document variables and attributes

### What are the relevant story cards/tickets? Any additional PRs or other references?

Jira: SURF 2103

## Before you request a review for this PR:

- [ ] For UI changes, did you manually test in recent versions of modern browsers (Chrome, Firefox, and Safari)?
- [ ] For UI changes, did you manually test in IE11 and legacy Edge?
- [ ] Did you add component tests for any new code?
- [ ] Did you run the component unit tests via `yarn test` to ensure all tests passed?
- [ ] Did you include a screenshot of the component tests?
- [ ] If you changed/added functionality, did you update the demo page and documentation?
- [ ] If needed, did you add or modify the demo test page to test the changed/added functionality?
- [ ] Did you assign reviewers?
- [ ] In Jira, have you linked to this PR on the ticket(s)?

2020-12-09 09:40 UTC, BY00565233 commented on src/scss/components/choice-tile/mixins/_hxChoiceTile.scss
>      background-color: $red-100;
Please write : background-color: var(--hxChoiceTile-invalid-hover-bgcolor, $red-100);

2020-12-09 09:40 UTC, BY00565233 commented on src/scss/components/choice-tile/mixins/_hxChoiceTile.scss
>      border-color: $red-900;
Please write : border-color : var(--hxChoiceTile-invalid-hover-bordercolor, $red-900);

2020-12-09 14:45 UTC, lalithkarikelli commented on src/scss/components/choice-tile/mixins/_hxChoiceTile.scss
>      background-color: $red-100;
Changes have been done, please review.

2020-12-09 14:45 UTC, lalithkarikelli commented on src/scss/components/choice-tile/mixins/_hxChoiceTile.scss
>      border-color: $red-900;
Changes have been done, please review.

2020-12-14 07:45 UTC, BY00565233 approved these changes
DEV LGTM

2021-01-19 21:21 UTC, 100stacks requested changes
### Please rebase and fix merge conflicts.

2021-01-21 12:51 UTC, lalithkarikelli commented
> ### Please rebase and fix merge conflicts.

@100stacks fixed merge conflicts ,rebased with master, added new variables and squashed the commits

2021-02-02 22:45 UTC, 100stacks approved these changes
@lalithkarikelli, we'll work on small mods to variable naming at a future time.

Dev LGTM.

2021-02-02 22:45 UTC, merged