refactor(hx-choicetile): update component specs
HelixDesignSystem/helix-ui pull request #814
Opened 2020-12-23 14:51 UTC by lalithkarikelli

## Description

`<hx-choicetile>`:  implementing color palette 2.0 styles

### What are the relevant story cards/tickets? Any additional PRs or other references?

Jira: SURF2153

## Before you request a review for this PR:

- [ ] For UI changes, did you manually test in recent versions of modern browsers (Chrome, Firefox, and Safari)?
- [ ] For UI changes, did you manually test in IE11 and legacy Edge?
- [ ] Did you add component tests for any new code?
- [ ] Did you run the component unit tests via `yarn test` to ensure all tests passed?
- [ ] Did you include a screenshot of the component tests?
- [ ] If you changed/added functionality, did you update the demo page and documentation?
- [ ] If needed, did you add or modify the demo test page to test the changed/added functionality?
- [ ] Did you assign reviewers?
- [ ] In Jira, have you linked to this PR on the ticket(s)?

2021-01-12 08:05 UTC, BY00565233 approved these changes
DEV LGTM

2021-01-12 21:05 UTC, danielmdesigns requested changes
I realized the design spec was not correct for Option Tiles. I have updated Abstract Style Guide specs.

1. Tile icons should match that of the state (hover, pressed)
2. I also included a disabled state

My apologies for overlooking these. Please update these two and let me know when I can take another look. That should solve any issues I have.

2021-01-13 11:56 UTC, lalithkarikelli commented
> I realized the design spec was not correct for Option Tiles. I have updated Abstract Style Guide specs.
> 
> 1. Tile icons should match that of the state (hover, pressed)
> 2. I also included a disabled state
> 
> My apologies for overlooking these. Please update these two and let me know when I can take another look. That should solve any issues I have.

@danielmdesigns i have pushed the changes , please review at https://deploy-preview-814--helix-ui.netlify.app/components/choice-tile . Thanks !

2021-01-13 16:22 UTC, 100stacks requested changes
@lalithkarikelli, it looks like we have legacy box shadow focus styles on Choice Tile:

<img width="796" alt="Screen Shot 2021-01-13 at 10 16 29 AM" src="https://user-images.githubusercontent.com/10120600/104479371-fc324c00-5588-11eb-89f7-097bc40bd18e.png">

<img width="794" alt="Screen Shot 2021-01-13 at 10 16 40 AM" src="https://user-images.githubusercontent.com/10120600/104479459-11a77600-5589-11eb-8c7b-600e618dfc20.png">

#### Please see https://deploy-preview-814--helix-ui.netlify.app/components/choice-tile/test.html

2021-01-14 20:54 UTC, 100stacks requested changes
Please update the focus state `box-shadow`.

2021-01-14 20:54 UTC, 100stacks commented on src/scss/components/choice-tile/mixins/_hxChoiceTile.scss
>      box-shadow: $focus-glow;
Please update to:

```css
box-shadow: 0 0 4px rgba($magenta-700, 0.5);
```

2021-01-15 07:36 UTC, lalithkarikelli commented on src/scss/components/choice-tile/mixins/_hxChoiceTile.scss
>      box-shadow: $focus-glow;
Changes have been done, please review.

2021-01-15 18:05 UTC, 100stacks approved these changes
Dev LGTM

2021-01-15 18:33 UTC, 100stacks commented on docs/components/icon/index.html
> +        <hx-icon type="information" style="color: #296CDC" class="size-2x"></hx-icon>
From PR #823 - update the demo to use the new icon type.

2021-01-15 18:33 UTC, 100stacks commented on docs/components/icon/index.html
> +          <hx-icon type="information" style="color: #296CDC"></hx-icon>
From PR #823 - update the demo to use the new icon type.

2021-01-15 20:37 UTC, danielmdesigns requested changes
We need to update the invalid color to match status color #D6251F

2021-01-15 20:56 UTC, 100stacks reviewed
> We need to update the invalid color to match status color #D6251F

@danielmdesigns, invalid status color updated.  Please see update.

2021-01-15 21:07 UTC, 100stacks approved these changes
@danielmdesigns, I'm going to go ahead and merge this PR #814 so that we can include it in today's release.  

We can make any other changes in a fast follow.  Thanks.

2021-01-15 21:08 UTC, merged