docs(hx-file): implement and document attributes and variables
HelixDesignSystem/helix-ui pull request #828
Opened 2021-02-08 13:41 UTC by BY00565233

## Description

`<hx-file>` : implement and document attributes and variables

### What are the relevant story cards/tickets? Any additional PRs or other references?

Jira: SURF-2107

## Before you request a review for this PR:

- [ ] For UI changes, did you manually test in recent versions of modern browsers (Chrome, Firefox, and Safari)?
- [ ] For UI changes, did you manually test in IE11 and legacy Edge?
- [ ] Did you add component tests for any new code?
- [ ] Did you run the component unit tests via `yarn test` to ensure all tests passed?
- [ ] Did you include a screenshot of the component tests?
- [ ] If you changed/added functionality, did you update the demo page and documentation?
- [ ] If needed, did you add or modify the demo test page to test the changed/added functionality?
- [ ] Did you assign reviewers?
- [ ] In Jira, have you linked to this PR on the ticket(s)?

2021-02-24 23:51 UTC, 100stacks requested changes
### @BY00565233, please check and verify these updates work in IE11 and Legacy Edge along with Firefox, Safari, and Chrome.

2021-03-01 14:41 UTC, BY00565233 commented
> ### @BY00565233, please check and verify these updates work in IE11 and Legacy Edge along with Firefox, Safari, and Chrome.

@100stacks I verified and updated the code to work in all 5 browsers . please review

2021-03-03 02:58 UTC, 100stacks requested changes

2021-03-03 02:58 UTC, 100stacks commented on src/scss/components/file/_hx-file-tile.scss
> +    border-color: var(--hxFile-hxFileTile-invalid-border-color, $red-status-900);
Please change [invalid] status colors to `$red-status-500`.

2021-03-03 15:43 UTC, lalithkarikelli approved these changes
DEV LGTM

2021-03-03 15:59 UTC, 100stacks approved these changes
Dev LGTM

2021-03-03 16:00 UTC, merged