docs(hx-radio): implement and document variables and attributes
HelixDesignSystem/helix-ui pull request #836
Opened 2021-02-22 13:20 UTC by lalithkarikelli

## Description

`<hx-radio>` : Implement and document attribute and variables

### What are the relevant story cards/tickets? Any additional PRs or other references?

Jira: SURF 2123

## Before you request a review for this PR:

- [ ] For UI changes, did you manually test in recent versions of modern browsers (Chrome, Firefox, and Safari)?
- [ ] For UI changes, did you manually test in IE11 and legacy Edge?
- [ ] Did you add component tests for any new code?
- [ ] Did you run the component unit tests via `yarn test` to ensure all tests passed?
- [ ] Did you include a screenshot of the component tests?
- [ ] If you changed/added functionality, did you update the demo page and documentation?
- [ ] If needed, did you add or modify the demo test page to test the changed/added functionality?
- [ ] Did you assign reviewers?
- [ ] In Jira, have you linked to this PR on the ticket(s)?

2021-02-24 23:37 UTC, 100stacks requested changes
### @lalithkarikelli, please verify these updates work in IE11 and Legacy Edge.

2021-02-26 15:46 UTC, lalithkarikelli commented
> ### @lalithkarikelli, please verify these updates work in IE11 and Legacy Edge.

@100stacks verified and updated code to work in all 5 browsers . please review

2021-02-26 17:08 UTC, 100stacks requested changes
### Based on feedback in PR #814, please update invalid state color to **$red-status-500**.

2021-02-26 17:08 UTC, 100stacks commented on src/scss/components/radio/mixins/_hxRadioControl.scss
>        color: $red-status-900;
Please update to **$red-status-500**.

2021-02-26 17:08 UTC, 100stacks commented on src/scss/components/radio/mixins/_hxRadioControl.scss
> +      color: var(--hxRadio-invalid-radio-hover-ie-color, $red-status-900);
Please update to **$red-status-500**.

2021-02-26 17:08 UTC, 100stacks commented on src/scss/components/radio/mixins/_hxRadioControl.scss
>      color: $red-status-900;
Please update to **$red-status-500**.

2021-02-26 17:08 UTC, 100stacks commented on src/scss/components/radio/mixins/_hxRadioControl.scss
> +    color: var(--hxRadio-invalid-radio-color, $red-status-900);
Please update to **$red-status-500**.

2021-02-26 17:08 UTC, 100stacks commented on src/scss/components/radio/mixins/_hxRadioFacade.scss
>      color: $red-status-900;
Please update to **$red-status-500**.

2021-02-26 17:08 UTC, 100stacks commented on src/scss/components/radio/mixins/_hxRadioFacade.scss
> +    color: var(--hxRadio-invalid-radio-facade-hover-color, $red-status-900);
Please update to **$red-status-500**.

2021-02-26 17:08 UTC, 100stacks commented on src/scss/components/radio/mixins/_hxRadioFacade.scss
>      color: $red-status-900;
Please update to **$red-status-500**.

2021-02-26 17:08 UTC, 100stacks commented on src/scss/components/radio/mixins/_hxRadioFacade.scss
> +    color: var(--hxRadio-invalid-radio-facade-color, $red-status-900);
Please update to **$red-status-500**.

2021-03-01 12:59 UTC, lalithkarikelli commented on src/scss/components/radio/mixins/_hxRadioControl.scss
>        color: $red-status-900;
Changes have been done, please review.

2021-03-01 12:59 UTC, lalithkarikelli commented on src/scss/components/radio/mixins/_hxRadioControl.scss
> +      color: var(--hxRadio-invalid-radio-hover-ie-color, $red-status-900);
Changes have been done, please review.

2021-03-01 12:59 UTC, lalithkarikelli commented on src/scss/components/radio/mixins/_hxRadioControl.scss
>      color: $red-status-900;
Changes have been done, please review.

2021-03-01 12:59 UTC, lalithkarikelli commented on src/scss/components/radio/mixins/_hxRadioControl.scss
> +    color: var(--hxRadio-invalid-radio-color, $red-status-900);
Changes have been done, please review.

2021-03-01 12:59 UTC, lalithkarikelli commented on src/scss/components/radio/mixins/_hxRadioFacade.scss
>      color: $red-status-900;
Changes have been done, please review.

2021-03-01 12:59 UTC, lalithkarikelli commented on src/scss/components/radio/mixins/_hxRadioFacade.scss
> +    color: var(--hxRadio-invalid-radio-facade-hover-color, $red-status-900);
Changes have been done, please review.

2021-03-01 12:59 UTC, lalithkarikelli commented on src/scss/components/radio/mixins/_hxRadioFacade.scss
>      color: $red-status-900;
Changes have been done, please review.

2021-03-01 12:59 UTC, lalithkarikelli commented on src/scss/components/radio/mixins/_hxRadioFacade.scss
> +    color: var(--hxRadio-invalid-radio-facade-color, $red-status-900);
Changes have been done, please review.

2021-03-02 09:06 UTC, BY00565233 approved these changes
DEV LGTM

2021-03-03 02:11 UTC, 100stacks approved these changes
DEV LGTM

2021-03-03 02:13 UTC, merged