refactor(hx-radio): refactor to use design tokens
HelixDesignSystem/helix-ui pull request #862
Opened 2021-04-08 12:52 UTC by lalithkarikelli

## Description

`<hx-radio>` : Added design tokens

### What are the relevant story cards/tickets? Any additional PRs or other references?

Jira: SURF2204

## Before you request a review for this PR:

- [ ] For UI changes, did you manually test in recent versions of modern browsers (Chrome, Firefox, and Safari)?
- [ ] For UI changes, did you manually test in IE11 and legacy Edge?
- [ ] Did you add component tests for any new code?
- [ ] Did you run the component unit tests via `yarn test` to ensure all tests passed?
- [ ] Did you include a screenshot of the component tests?
- [ ] If you changed/added functionality, did you update the demo page and documentation?
- [ ] If needed, did you add or modify the demo test page to test the changed/added functionality?
- [ ] Did you assign reviewers?
- [ ] In Jira, have you linked to this PR on the ticket(s)?

2021-04-19 22:35 UTC, 100stacks requested changes
Let's hold off on removing states for now.

2021-04-20 14:31 UTC, lalithkarikelli commented on src/scss/components/radio/_index.scss
> +    color: $rax-component-radio-label-default-color; // in tokens it is $gray-900
Changes have been done, please review.

2021-04-20 14:31 UTC, lalithkarikelli commented on src/scss/components/radio/_index.scss
> +    background-color: $rax-component-radio-default-background-color;
Changes have been done, please review.

2021-04-20 14:31 UTC, lalithkarikelli commented on src/scss/components/radio/_index.scss
> +    color: $rax-component-radio-default-border-color; // in tokens it is border-color
Changes have been done, please review.

2021-04-20 14:31 UTC, lalithkarikelli commented on src/scss/components/radio/_index.scss
> +      color: $rax-component-radio-checked-border-color;// in tokens it is border-color
Changes have been done, please review.

2021-04-20 14:32 UTC, lalithkarikelli commented on src/scss/components/radio/_index.scss
> +        color: $rax-component-radio-checked-border-color;// no specific token for checked label color
Changes have been done, please review.

2021-04-20 14:32 UTC, lalithkarikelli commented on src/scss/components/radio/_index.scss
> +    color: $rax-component-radio-label-default-color; // in tokens it is $gray-900
Changes have been done, please review.

2021-04-20 14:32 UTC, lalithkarikelli commented on src/scss/components/radio/_index.scss
> +    background-color: $rax-component-radio-default-background-color;
Changes have been done, please review.

2021-04-20 14:32 UTC, lalithkarikelli commented on src/scss/components/radio/_index.scss
> +      color: $rax-component-radio-checked-border-color;// in tokens it is border-color
Changes have been done, please review.

2021-04-20 14:32 UTC, lalithkarikelli commented on src/scss/components/radio/_index.scss
> +        color: $rax-component-radio-checked-border-color;// no specific token for checked label color
Changes have been done, please review.

2021-04-20 14:33 UTC, lalithkarikelli commented on src/scss/components/radio/mixins/_hxRadioControl.scss
> +    color: $rax-component-radio-hover-border-color;
Changes have been done, please review.

2021-04-20 14:33 UTC, lalithkarikelli commented on src/scss/components/radio/mixins/_hxRadioControl.scss
> +      background-color: $rax-component-radio-hover-background-color;
Changes have been done, please review.

2021-04-20 14:33 UTC, lalithkarikelli commented on src/scss/components/radio/mixins/_hxRadioControl.scss
> +      color: $rax-component-radio-hover-border-color;
Changes have been done, please review.

2021-04-20 14:33 UTC, lalithkarikelli commented on src/scss/components/radio/mixins/_hxRadioControl.scss
> +    color: $rax-component-radio-default-border-color;
Changes have been done, please review.

2021-04-20 14:33 UTC, lalithkarikelli commented on src/scss/components/radio/mixins/_hxRadioControl.scss
> +      background-color: $rax-component-radio-default-background-color;
Changes have been done, please review.

2021-04-20 14:33 UTC, lalithkarikelli commented on src/scss/components/radio/mixins/_hxRadioControl.scss
> +    color: $rax-component-radio-invalid-border-color;
Changes have been done, please review.

2021-04-20 14:33 UTC, lalithkarikelli commented on src/scss/components/radio/mixins/_hxRadioControl.scss
> +    color: $rax-component-radio-disabled-border-color;
Changes have been done, please review.

2021-04-20 14:34 UTC, lalithkarikelli commented on src/scss/components/radio/mixins/_hxRadioFacade.scss
> +    background-color: $rax-component-radio-default-background-color;
Changes have been done, please review.

2021-04-20 14:34 UTC, lalithkarikelli commented on src/scss/components/radio/mixins/_hxRadioFacade.scss
> +  color: $rax-component-radio-disabled-border-color;
Changes have been done, please review.

2021-04-20 14:34 UTC, lalithkarikelli commented on docs/components/radio/test.html
> -          <tr>
Changes have been done, please review.

2021-04-20 14:34 UTC, lalithkarikelli commented on src/scss/components/radio/_index.scss
> -  }
Changes have been done, please review.

2021-04-20 14:34 UTC, lalithkarikelli commented on src/scss/components/radio/_index.scss
> -
Changes have been done, please review.

2021-04-20 14:34 UTC, lalithkarikelli commented on src/scss/components/radio/_index.scss
> -      }
Changes have been done, please review.

2021-04-20 14:35 UTC, lalithkarikelli commented on src/scss/components/radio/mixins/_hxRadioControl.scss
> -    }
Changes have been done, please review.

2021-04-20 14:35 UTC, lalithkarikelli commented on src/scss/components/radio/mixins/_hxRadioControl.scss
> -    }
Changes have been done, please review.

2021-04-20 14:35 UTC, lalithkarikelli commented on src/scss/components/radio/mixins/_hxRadioFacade.scss
> -  }
Changes have been done, please review.

2021-04-20 14:35 UTC, lalithkarikelli commented on src/scss/components/radio/mixins/_hxRadioFacade.scss
> -  }
Changes have been done, please review.

2021-04-20 14:36 UTC, lalithkarikelli commented
Rebased with master and squashed all commits

2021-04-21 09:02 UTC, badejayayesubabu approved these changes
DEV LGTM

2021-04-21 22:35 UTC, 100stacks approved these changes
Dev LGTM

2021-04-21 22:36 UTC, merged